//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTheListString", ReplyAction="http://tempuri.org/IService1/getTheListStringResponse")]
        string[] getTheListString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTheListString", ReplyAction="http://tempuri.org/IService1/getTheListStringResponse")]
        System.Threading.Tasks.Task<string[]> getTheListStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeToDo", ReplyAction="http://tempuri.org/IService1/removeToDoResponse")]
        bool removeToDo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeToDo", ReplyAction="http://tempuri.org/IService1/removeToDoResponse")]
        System.Threading.Tasks.Task<bool> removeToDoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToDo", ReplyAction="http://tempuri.org/IService1/addToDoResponse")]
        void addToDo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToDo", ReplyAction="http://tempuri.org/IService1/addToDoResponse")]
        System.Threading.Tasks.Task addToDoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IService1>, ConsoleApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getTheListString() {
            return base.Channel.getTheListString();
        }
        
        public System.Threading.Tasks.Task<string[]> getTheListStringAsync() {
            return base.Channel.getTheListStringAsync();
        }
        
        public bool removeToDo(int id) {
            return base.Channel.removeToDo(id);
        }
        
        public System.Threading.Tasks.Task<bool> removeToDoAsync(int id) {
            return base.Channel.removeToDoAsync(id);
        }
        
        public void addToDo() {
            base.Channel.addToDo();
        }
        
        public System.Threading.Tasks.Task addToDoAsync() {
            return base.Channel.addToDoAsync();
        }
    }
}
